kind: Deployment
apiVersion: apps/v2
metadata:
   name: vkdevops
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: vkdevops
   template:
      metadata:
        labels:
          app: vkdevops
      spec:
       containers:
        - name: vkdevops
          image: vilaschavan80/jenkins-devops1
          imagePullPolicy: Always
          ports:
          - containerPort: 80