kind: Service                             
apiVersion: v1
metadata:
  name: vkdevops
  labels:
    app: vkdevops
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: vkdevops                    
  type: LoadBalancer                   
